package wonky.product.materialyoucatalog.ui.theme.deeporange
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFB22C01)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBD1)
val md_theme_light_onPrimaryContainer = Color(0xFF3B0800)
val md_theme_light_secondary = Color(0xFF77574E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBD1)
val md_theme_light_onSecondaryContainer = Color(0xFF2C150F)
val md_theme_light_tertiary = Color(0xFF6C5D2E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF6E1A6)
val md_theme_light_onTertiaryContainer = Color(0xFF231B00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A19)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A19)
val md_theme_light_surfaceVariant = Color(0xFFF5DED8)
val md_theme_light_onSurfaceVariant = Color(0xFF53433F)
val md_theme_light_outline = Color(0xFF85736E)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEEB)
val md_theme_light_inverseSurface = Color(0xFF362F2D)
val md_theme_light_inversePrimary = Color(0xFFFFB5A1)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFB22C01)
val md_theme_light_outlineVariant = Color(0xFFD8C2BC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB5A1)
val md_theme_dark_onPrimary = Color(0xFF601300)
val md_theme_dark_primaryContainer = Color(0xFF881F00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBD1)
val md_theme_dark_secondary = Color(0xFFE7BDB2)
val md_theme_dark_onSecondary = Color(0xFF442A23)
val md_theme_dark_secondaryContainer = Color(0xFF5D4038)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBD1)
val md_theme_dark_tertiary = Color(0xFFD9C58D)
val md_theme_dark_onTertiary = Color(0xFF3B2F05)
val md_theme_dark_tertiaryContainer = Color(0xFF534619)
val md_theme_dark_onTertiaryContainer = Color(0xFFF6E1A6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A19)
val md_theme_dark_onBackground = Color(0xFFEDE0DD)
val md_theme_dark_surface = Color(0xFF201A19)
val md_theme_dark_onSurface = Color(0xFFEDE0DD)
val md_theme_dark_surfaceVariant = Color(0xFF53433F)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BC)
val md_theme_dark_outline = Color(0xFFA08C88)
val md_theme_dark_inverseOnSurface = Color(0xFF201A19)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DD)
val md_theme_dark_inversePrimary = Color(0xFFB22C01)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB5A1)
val md_theme_dark_outlineVariant = Color(0xFF53433F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFBF360C)
